def gv

pipeline {
    agent any
    stages {
        stage('Init') {
            steps {
                script {
                    echo 'Initializing...'
                    dir('Exercises/BuildAutomationCICDWithJenkins/jenkins-exercises/app') {
                        gv = load 'script.groovy'
                        sh 'npm version minor --no-git-tag-version'
                    }
                    sh 'npm -v'
                    env.VERSION = '1.0.0'
                }
            }
        }
        stage("Test") {
            steps {
                script {
                    gv.testApp()
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    gv.buildDockerImage()
                }
            }
        }
        stage('Commit and Push Git Changes') {
            steps {
                script {
                    echo 'Commiting and pushing updated version to Git...'
                }
            }
        }
    }
}