services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mysqldb
    networks:
      - mysql-network
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    links:
      - mysql:db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - mysql-network

  my-app:
      image: 307946634191.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0

      ports: 
        - 8080:8080
      
      environment:
        - DB_USER=user
        - DB_PWD=password
        - DB_SERVER=mysql
        - DB_NAME=mysqldb
      
      networks:
        - mysql-network

networks:
  mysql-network:
    driver: bridge
