services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQl_DATABASE=mysqldb
    networks:
      - mysql-network
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql:db
    environment:
      - name=value
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
